name: Sync Labels

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Sync labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true