name: Sync Labels

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
          dry-run: true