name: Node.js CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/labels.yml"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/labels.yml"
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  verify_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        env:
          LEFTHOOK: 0
        run: npm ci
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Verify Lint/Format
        if: github.event_name == 'pull_request'
        run: npx ultracite check --quiet --type-aware --type-check --format=github
      - name: Build
        run: npm run build --if-present